// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CanUndoDeleteConfigFile(rawCoreType: string): $CancellablePromise<boolean> {
    return $Call.ByID(2860862145, rawCoreType);
}

export function CheckAppUpdate(): $CancellablePromise<$models.AppUpdateInfo> {
    return $Call.ByID(957133460);
}

export function CheckUpdate(currentVersion: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2721282167, currentVersion, rawCoreType);
}

export function DeleteConfigFile(rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2839170645, rawFileName, rawCoreType);
}

export function DownloadConfig(rawURL: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3689975968, rawURL, rawCoreType);
}

export function DownloadCore(currentVersion: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2731700857, currentVersion, rawCoreType);
}

export function ForceCheckUpdate(currentVersion: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1671274230, currentVersion, rawCoreType);
}

export function GetAppUpdateInfo(): $CancellablePromise<$models.AppUpdateInfo> {
    return $Call.ByID(1378356932);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3044026275);
}

export function GetConfig(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2439653156);
}

export function GetConfigForType(rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(798218691, rawCoreType);
}

export function GetSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3946130123);
}

export function ImportConfig(rawContent: string, sourceFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(579250609, rawContent, sourceFileName, rawCoreType);
}

export function InstallAppUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1482439629);
}

export function ListConfigFiles(rawCoreType: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2883527251, rawCoreType);
}

export function OpenCoreLog(rawCoreType: string): $CancellablePromise<void> {
    return $Call.ByID(722706685, rawCoreType);
}

export function RestartCore(rawArgs: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2020121754, rawArgs, rawCoreType);
}

export function SaveBehavior(runAsAdmin: boolean, autoStart: boolean, autoStartSingBox: boolean, autoStartMihomo: boolean, stopCoreOnExit: boolean, backendDebugLog: boolean, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(872427917, runAsAdmin, autoStart, autoStartSingBox, autoStartMihomo, stopCoreOnExit, backendDebugLog, rawCoreType);
}

export function SaveChannel(rawChannel: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(825658706, rawChannel, rawCoreType);
}

export function SaveConfigFileName(rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3218160460, rawFileName, rawCoreType);
}

export function SaveCoreType(rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3983412536, rawCoreType);
}

export function SaveRunArgs(rawArgs: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1182958737, rawArgs, rawCoreType);
}

export function SaveURL(rawURL: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3210647596, rawURL, rawCoreType);
}

export function SelectConfigFile(rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1276464918, rawFileName, rawCoreType);
}

export function SetTrayAPI(rawURL: string, rawSecret: string): $CancellablePromise<void> {
    return $Call.ByID(879970318, rawURL, rawSecret);
}

export function StartCore(rawArgs: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(879345873, rawArgs, rawCoreType);
}

export function StopCore(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1224211689);
}

export function UndoDeleteConfigFile(rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(132981571, rawCoreType);
}
