// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CanUndoDeleteConfigFile(rawCoreType: string): $CancellablePromise<boolean> {
    return $Call.ByID(2860862145, rawCoreType);
}

export function CheckAppUpdate(): $CancellablePromise<$models.AppUpdateInfo> {
    return $Call.ByID(957133460);
}

export function CheckUpdate(rawURL: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2721282167, rawURL, rawCoreType);
}

export function ClearTrafficData(): $CancellablePromise<void> {
    return $Call.ByID(2270706196);
}

export function DeleteConfigFile(rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2839170645, rawFileName, rawCoreType);
}

export function DownloadConfig(rawURL: string, rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3689975968, rawURL, rawFileName, rawCoreType);
}

export function DownloadCore(rawURL: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2731700857, rawURL, rawCoreType);
}

export function ForceCheckUpdate(rawURL: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1671274230, rawURL, rawCoreType);
}

export function GetAppUpdateInfo(): $CancellablePromise<$models.AppUpdateInfo> {
    return $Call.ByID(1378356932);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3044026275);
}

export function GetCoreState(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3259379246);
}

export function GetCoreStateForType(rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(4278355373, rawCoreType);
}

export function GetSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3946130123);
}

export function GetTrafficMeta(): $CancellablePromise<$models.TrafficMeta> {
    return $Call.ByID(455041338);
}

export function GetTrafficRank(req: $models.TrafficRankRequest): $CancellablePromise<$models.TrafficRankResult> {
    return $Call.ByID(3721033365, req);
}

export function ImportConfig(rawContent: string, sourceFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(579250609, rawContent, sourceFileName, rawCoreType);
}

export function InstallAppUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1482439629);
}

export function ListConfigFiles(rawCoreType: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2883527251, rawCoreType);
}

export function OpenCoreLog(rawCoreType: string): $CancellablePromise<void> {
    return $Call.ByID(722706685, rawCoreType);
}

export function RestartCore(rawArgs: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2020121754, rawArgs, rawCoreType);
}

export function SelectConfigFile(rawFileName: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1276464918, rawFileName, rawCoreType);
}

export function SetTrafficAutoClean(interval: string): $CancellablePromise<void> {
    return $Call.ByID(765301969, interval);
}

export function StartCore(rawArgs: string, rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(879345873, rawArgs, rawCoreType);
}

export function StopCore(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(1224211689);
}

export function UndoDeleteConfigFile(rawCoreType: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(132981571, rawCoreType);
}

export function UpdateCoreSettings(patch: $models.CoreSettingsPatch): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(934907905, patch);
}
