// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppUpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseURL": string;
    "releaseNotes": string;
    "publishedAt": string;
    "downloadURL": string;
    "assetSize": number;
}

export interface CoreConfig {
    "coreType": string;
    "version": string;
    "versionDetail": string;
    "channel": string;
    "corePath": string;
    "installedVersion": string;
    "installed": boolean;
    "latestVersion": string;
    "updateAvailable": boolean;
    "runArgs": string;
    "configURL": string;
    "configFileName": string;
    "running": boolean;
    "pid": number;
    "logPath": string;
    "coreLogError": boolean;
    "configPath": string;
    "configAvailable": boolean;
    "runAsAdmin": boolean;
    "isAdmin": boolean;
    "autoStart": boolean;
    "autoStartSingBox": boolean;
    "autoStartMihomo": boolean;
    "backendDebugLog": boolean;
    "stopCoreOnExit": boolean;
    "clashApiUrl": string;
    "clashApiHost": string;
    "clashApiPort": string;
    "clashApiSecret": string;
}

export interface CoreSettingsPatch {
    "coreType": string;
    "channel"?: string | null;
    "runArgs"?: string | null;
    "runAsAdmin"?: boolean | null;
    "autoStart"?: boolean | null;
    "autoStartSingBox"?: boolean | null;
    "autoStartMihomo"?: boolean | null;
    "stopCoreOnExit"?: boolean | null;
    "backendDebugLog"?: boolean | null;
}
