// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CoreConfig {
    "coreType": string;
    "urlTemplate": string;
    "configuredVersion": string;
    "version": string;
    "versionDetail": string;
    "channel": string;
    "corePath": string;
    "installedVersion": string;
    "installed": boolean;
    "latestVersion": string;
    "updateAvailable": boolean;
    "runArgs": string;
    "configURL": string;
    "configFileName": string;
    "running": boolean;
    "pid": number;
    "logPath": string;
    "configPath": string;
    "configAvailable": boolean;
    "runAsAdmin": boolean;
    "autoStart": boolean;
    "autoStartSingBox": boolean;
    "autoStartMihomo": boolean;
    "backendDebugLog": boolean;
    "trayAPIURL": string;
}
