// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckUpdate(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2721282167);
}

export function DownloadCore(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2731700857);
}

export function GetConfig(): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(2439653156);
}

export function SaveURL(rawURL: string): $CancellablePromise<$models.CoreConfig> {
    return $Call.ByID(3210647596, rawURL);
}
