// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CoreConfig {
    "urlTemplate": string;
    "version": string;
    "channel": string;
    "corePath": string;
    "installedVersion": string;
    "installed": boolean;
    "latestVersion": string;
    "updateAvailable": boolean;
}
