// Cynhyrchwyd y ffeil hon yn awtomatisch. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CoreConfig {
    "urlTemplate": string;
    "configuredVersion": string;
    "version": string;
    "versionDetail": string;
    "channel": string;
    "corePath": string;
    "installedVersion": string;
    "installed": boolean;
    "latestVersion": string;
    "updateAvailable": boolean;
    "backupVersion": string;
    "backupAvailable": boolean;
    "pendingVersion": string;
    "updatePending": boolean;
    "runArgs": string;
    "configURL": string;
    "running": boolean;
    "pid": number;
    "logPath": string;
    "configPath": string;
    "configAvailable": boolean;
    "runAsAdmin": boolean;
    "autoStart": boolean;
    "autoStartCore": boolean;
}
